baseurl = "http://snippets.studybreakmedia.com.s3-website-us-east-1.amazonaws.com/gcs"
languageCode = "en-us"
title = "GCS callback isoloation"

canonifyurls = false
disableRSS = false
buildDrafts = false

publishdir = 'gcs'

[permalinks]
    article = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"

[params]
    author = "Jononomo"


